name: Ohe-testing

on:
  push:
    branches: 
      - develop1.0
    paths:
      - 'sushi-config.yaml'
      - 'input/**'
      - 'custom-template/**'
  pull_request:
    branches: [ develop1.0 ]
    
jobs:
  turn:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.0']
    steps:
    - uses: actions/checkout@v2

    - name: Setup npm
      uses: actions/setup-node@v2
      with: 
        check-latest: true

    - name: Setup Sushi
      run: |
        sudo npm install -g fsh-sushi
    - name: Install Jekyll
      run: |
        sudo apt-get install jekyll

    # -- DUMMY download from here
    - name: Download IG Publisher
      uses: Legion2/download-release-action@v2.1.0
      with:
        repository: HL7/fhir-ig-publisher
        tag: 'latest'
        path: .
        file: publisher.jar
    # -- DUMMY download until here

    - name: Wget IG PublisherJPFHIR
      uses: wei/wget@v1
      with:
        args:  https://tx.jpfhir.jp/download/publisherJPFHIR.jar

    - name: Run IG Publisher
      env:
        PACKAGE: jp-core.draft1#1.1.0-beta
      run: | 
        mkdir input-cache
        mv ./publisherJPFHIR.jar ./input-cache
        : # mv ./publisher.jar ./input-cache
        : # this is a comment:  ls -la ./input-cache
        mkdir /home/runner/.fhir
        mkdir /home/runner/.fhir/packages
        mkdir /home/runner/.fhir/packages/$PACKAGE
        : # local cache にpackage をcopyして展開する
        cp ./packages_snapshot/$PACKAGE.tgz /home/runner/.fhir/packages/$PACKAGE/$PACKAGE.tgz
        tar xzf /home/runner/.fhir/packages/$PACKAGE/$PACKAGE.tgz -C /home/runner/.fhir/packages/$PACKAGE/
        unset DISPLAY
        : # 
        java -Djava.awt.headless=true -jar ./input-cache/publisherJPFHIR.jar -ig ig.ini  -tx https://tx.jpfhir.jp
        : # java -Djava.awt.headless=true -jar ./input-cache/publisher.jar -ig ig.ini
        
    - name: Deploy Implementation Guide
      if: success()
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.PERSONAL_TOKEN }}
        external_repository: kazuhiko-ohe/jp-core-develop
        publish_branch: develop1.0-pages
        publish_dir: ./output
    - name: ssh key generate
      run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
      env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY_TO_JPFHIR }}
    - name: rsync remote-site-deploy
      run: rsync -auzrv -e "ssh -i key -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -p 8022" --delete ./output ./fsh-generated r2217734@www41.onamae.ne.jp:/home/r2217734/public_html/jpfhir.jp/fhir/ePrescriptionData/ --exclude .htaccess
